lr: 7e-4
critic_lr: 7e-4
episode_length: 200
run_dir: ./results/
log_interval: 5
use_recurrent_policy: true
use_joint_action_loss: true
use_valuenorm: true
use_adv_normalize: true
callbacks:
  - id: "ProgressBarCallback"
  - id: "CheckpointCallback"   # TODO: 保存表现最好的model和最新的model
    args: {
        "save_freq": 10, # how often to save the model, 需要乘上num_envs
        "save_path": "./checkpoints/go1football-defender/jrpo",  # where to save the model
        # "name_prefix": "jrpo", # the prefix of the saved model
    }
