lr: 7e-4
critic_lr: 7e-4
episode_length: 200
run_dir: ./results/
log_interval: 5
use_recurrent_policy: true
use_joint_action_loss: false
use_valuenorm: true
use_adv_normalize: true
callbacks:
  - id: "ProgressBarCallback"
  - id: "CheckpointCallback"
    args: {
        "save_freq": 5000, # how often to save the model, saving a model every save_freq calls to env.step().
        "save_path": "./checkpoints/go1football-defender/ppo_copy",  # where to save the model
        "name_prefix": "ppo", # the prefix of the saved model
    }